
---
name: Docker and NGINX Pipeline

on: 
  push:
    branches:
      - "main"
      - "develop"


  pull_request:
    branches:
      - "main"
      
  workflow_dispatch:

jobs:
  dockerfile-check:
    name: Check DockerFile
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile