
---
name: Docker and NGINX Pipeline

on: 
  push:
    branches:
      - "main"
      - "develop"


  pull_request:
    branches:
      - "main"
      
  workflow_dispatch:

jobs:

  html-sanity:
    name: HTML Check
    runs-on: ubuntu-22.04
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.2
        with:
          # Required:
          url: "https://..."
          # optional:
          honorRobotExclusions: false
          ignorePatterns: "github,google"
          recursiveLinks: false # Check all URLs on all reachable pages (could take a while)

      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"


  # Checkeo del DockerFile
  dockerfile-check:
    name: Check DockerFile
    runs-on: ubuntu-22.04
    needs: [html-sanity]
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile

  build-and-push:
    name: build and push image
    runs-on: ubuntu-22.04
    needs: [dockerfile-check]
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v1.0.2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}